# -*- coding: utf-8 -*-
"""Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iJfUjFKq1WcphVk_HWJ60jQf1ot0Jstr
"""

# Commented out IPython magic to ensure Python compatibility.
!pip install -q modal stable-baselines3 shimmy gymnasium sb3_contrib
# %matplotlib inline
import matplotlib.pyplot as plt

import os
import modal
import importlib

# --- 1. CLEANUP & RESET ---
# Remove any conflicting environment variables so Modal uses the config file.
os.environ.pop("MODAL_TOKEN_ID", None)
os.environ.pop("MODAL_TOKEN_SECRET", None)

# --- 2. AUTHENTICATION (CLI) ---
print("🔑 Setting up Modal Credentials...")
# We use the CLI to write the credentials to ~/.modal/config.toml
!modal token set --token-id ak-l27k8B20Zcg3pSxJkpSEPG --token-secret as-YwgHH2iudxNDtprER6DUZy

# --- 3. NVIDIA SECRET SETUP ---
print("\n🔒 Creating NVIDIA Secret...")
# Using your specific new key
os.environ["NVIDIA_API_KEY"] = "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"
!modal secret create --force nvidia-secret NVIDIA_API_KEY=$NVIDIA_API_KEY

# --- 4. DEPLOYMENT ---
print("\n☁️ Deploying Backend...")
!modal deploy fed_backend.py

# --- 5. VERIFICATION ---
print("\n📞 Verifying Connection...")
try:
    # Reload modal to ensure it reads the new config.toml
    importlib.reload(modal)

    # Connect to the deployed function
    f = modal.Function.from_name("fed-pomdp-backend", "get_market_sentiment")

    # Test call
    print("   > Sending test signal to cloud...")
    result = f.remote("The economy is stable.", 0.0)

    if result != 0.0:
        # Note: A "stable" headline with 0.0 bias might return 0.0, which is correct/neutral.
        # But getting a response means the connection worked.
        pass

    print(f"✅ SUCCESS! Backend responded. Sentiment Score: {result}")
    print("👉 You are now ready to run the full simulation.")

except Exception as e:
    print(f"❌ Connection failed: {e}")
    print("   Tip: If this fails, try Restarting Session (Runtime > Restart Session) and running this cell again.")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile fed_trainer_modal.py
# import modal
# import os
# import gymnasium as gym
# import numpy as np
# from gymnasium import spaces
# 
# # Define the Cloud Environment
# image = modal.Image.debian_slim().pip_install(
#     "stable-baselines3",
#     "shimmy",
#     "gymnasium",
#     "sb3_contrib",
#     "numpy"
# )
# 
# app = modal.App("fed-gpu-fleet")
# 
# # --- ENV DEFINITION ---
# class FedEnv(gym.Env):
#     def __init__(self, use_real_llm=False):
#         super(FedEnv, self).__init__()
#         self.use_real_llm = use_real_llm
# 
#         # --- 1. ACTION SPACE ---
#         self.ACTION_LOOKUP = {
#             0: (+0.75, +1.0), 1: (+0.50, +1.0), 2: (+0.25, +1.0),
#             3: (+0.25,  0.0), 4: (+0.25, -0.5), 5: ( 0.00, +1.0),
#             6: ( 0.00,  0.0), 7: ( 0.00, -1.0), 8: (-0.25,  0.0),
#             9: (-0.25, +0.5), 10:(-0.25, -1.0), 11:(-0.50, -1.0),
#             12:(-0.75, -1.0),
#         }
#         self.action_space = spaces.Discrete(13)
# 
#         # --- 2. OBSERVATION SPACE ---
#         self.observation_space = spaces.Box(
#             low=np.array([-10.0, 0.0, -2.0, -5.0, -1.0]),
#             high=np.array([50.0, 30.0, 2.0, 5.0, 1.0]),
#             dtype=np.float32
#         )
#         self.reset()
# 
#     def reset(self, seed=None):
#         super().reset(seed=seed)
#         self.t = 0
#         self.r_star = 2.0
#         self.u_star = 4.0
#         self.inflation = np.random.uniform(1.5, 3.5)
#         self.unemployment = np.random.uniform(3.5, 5.0)
#         self.policy_rate = self.r_star + self.inflation
#         self.expectations = self.inflation
# 
#         self.last_obs_pi = self.inflation
#         self.last_obs_u = self.unemployment
#         self.last_delta_r = 0.0
#         self.last_delta_u = 0.0
#         self.llm_score = 0.0
#         self.prev_u = self.unemployment
#         return self._get_obs(), {}
# 
#     def _get_obs(self):
#         return np.array([
#             self.last_obs_pi, self.last_obs_u, self.last_delta_r,
#             self.last_delta_u, self.llm_score
#         ], dtype=np.float32)
# 
#     def step(self, action_idx):
#         self.t += 1
#         is_meeting_week = (self.t % 2 != 0)
#         self.prev_u = self.unemployment
# 
#         # A. DECODE ACTION
#         delta_i, new_bias = self.ACTION_LOOKUP[action_idx]
#         self.policy_rate += delta_i
# 
#         # B. PHYSICS ENGINE (Low Noise Version)
#         real_rate = self.policy_rate - self.expectations
#         rate_gap = real_rate - self.r_star
# 
#         sensitivity = 0.1
#         if self.unemployment < 3.5: sensitivity = 0.2
#         elif self.unemployment > 8.0: sensitivity = 0.05
# 
#         # REDUCED NOISE: 0.1 -> 0.02 (Cleaner Signal)
#         shock = np.random.normal(0, 0.02)
#         self.unemployment += (sensitivity * rate_gap) + shock
# 
#         if self.unemployment < 1.0: self.unemployment = 1.0 + abs(shock)
# 
#         u_gap = self.unemployment - self.u_star
#         phillips = -0.2 * u_gap
#         if self.unemployment < 3.0: phillips *= 2.0
# 
#         # REDUCED NOISE: 0.2 -> 0.02
#         self.inflation += phillips + 0.5 * (self.expectations - self.inflation) + np.random.normal(0, 0.02)
# 
#         # Clipping
#         self.inflation = np.clip(self.inflation, -5.0, 50.0)
#         self.unemployment = np.clip(self.unemployment, 1.0, 30.0)
#         self.policy_rate = max(0.0, min(self.policy_rate, 20.0))
# 
#         self.expectations = 0.8 * self.expectations + 0.2 * self.inflation - 0.1 * new_bias
# 
#         # --- C. REWARD (Radiated Heat) ---
#         loss_pi = (self.inflation - 2.0)**2
#         loss_u_base = (self.unemployment - 4.0)**2
#         loss_u_fear = 0.0
#         if self.unemployment > 6.0:
#             loss_u_fear = (self.unemployment - 6.0) ** 4
# 
#         loss_volatility = 0.5 * (delta_i**2)
#         reward = -(loss_pi + loss_u_base + loss_u_fear + loss_volatility)
# 
#         terminated = self.t >= 100
# 
#         # D. OBSERVATION
#         delta_u_actual = self.unemployment - self.prev_u
#         if is_meeting_week:
#             # REDUCED OBSERVATION NOISE too
#             self.last_obs_pi = self.inflation + np.random.normal(0, 0.05)
#             self.last_obs_u = self.unemployment + np.random.normal(0, 0.05)
#             self.last_delta_r = delta_i
#             self.last_delta_u = delta_u_actual
#             self.llm_score = 0.0
#         else:
#             self.last_delta_r = 0.0
#             self.last_delta_u = 0.0
#             if new_bias > 0 and self.inflation > 2.5: self.llm_score = -0.5
#             elif new_bias < 0 and self.unemployment > 5.0: self.llm_score = -0.5
#             else: self.llm_score = 0.5
# 
#         return self._get_obs(), reward, terminated, False, {}
# 
# # --- TRAINER ---
# @app.function(image=image, gpu="T4", timeout=3600)
# def train_seed(seed: int):
#     from sb3_contrib import RecurrentPPO
#     from stable_baselines3.common.vec_env import DummyVecEnv, VecNormalize
#     import numpy as np
# 
#     print(f"[Seed {seed}] ⚙ Initializing Environment (Low Noise)...")
#     env = FedEnv(use_real_llm=False)
#     env = DummyVecEnv([lambda: env])
#     env = VecNormalize(env, norm_obs=True, norm_reward=True, clip_obs=10.)
# 
#     model = RecurrentPPO(
#         "MlpLstmPolicy",
#         env,
#         verbose=1,
#         learning_rate=0.0003,
#         n_steps=2048,
#         batch_size=64,
#         gamma=0.99,
#         gae_lambda=0.95,
#         seed=seed
#     )
# 
#     # INCREASED TRAINING TIME: 200k steps for convergence
#     print(f"[Seed {seed}] ↗ Starting Training (200k steps)...")
#     model.learn(total_timesteps=200000)
# 
#     model.save(f"fed_agent_{seed}")
#     env.save(f"vec_normalize_{seed}.pkl")
# 
#     with open(f"fed_agent_{seed}.zip", "rb") as f:
#         model_bytes = f.read()
#     with open(f"vec_normalize_{seed}.pkl", "rb") as f:
#         vec_bytes = f.read()
# 
#     return model_bytes, vec_bytes
# 
# @app.local_entrypoint()
# def main():
#     print("⚒ Launching Training on Modal (Seed 42)...\n")
#     model_bytes, vec_bytes = train_seed.remote(42)
#     print("\n✨ Agent Returned.")
#     with open("fed_agent_stable.zip", "wb") as f:
#         f.write(model_bytes)
#     with open("vec_normalize.pkl", "wb") as f:
#         f.write(vec_bytes)
#     print("✅ DONE! Optimized agent downloaded.")
# 
# ##To Run Use: modal run --detach fed_trainer_modal.py

"""## Run Training

### Subtask:
Execute the training script on Modal to train the new agent and download artifacts.

**Reasoning**:
Execute the training script on Modal to train the agent and download the artifacts.
"""

!modal run --detach fed_trainer_modal.py